apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "devsecops-demo.fullname" . }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "devsecops-demo.fullname" . }}
    weight: 100
  wildcardPolicy: None
